### ISSUE TITLE
您好，项目缺少数据库创建脚本

### ISSUE THREAD

**Issue by doudoubean** [PChief/GushiwenSpider#1]
如果添加上MySQL数据库创建脚本，就完美了

**Comment by PChief** [comment]
数据库结构与代码已经重新修改添加到https://github.com/PChief/GushiwenSpider/blob/master/gushiwen/spiders/%E6%95%B0%E6%8D%AE%E5%BA%93%E8%A1%A8%E7%BB%93%E6%9E%84.xlsx
